string map_name
# unit: m, rad
geometry_msgs/Pose2D start_pose
geometry_msgs/Pose2D end_pose
geometry_msgs/Pose2D[] path_coords
# unit: m/s
float64 linear_speed
# unit: rad/s
float64 angular_speed
# unit: m
float64 dece_distance
# unit: m
float64 stop_distance
# 0: linear, 1: curve
uint8 move_mode
# 0: head forwards, 1: head backwards
uint8 move_type
---
int32 ret_code
string ret_msg